### PR TITLE
Update to version 0.12.0

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by johanneskoester** [comment]
appveyor seems to fail because of an unrelated problem. @msarahan maybe rerendering the feedstock might help?

**Comment by jakirkham** [comment]
Yes, please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.0 (or soon 2.4.1). Either should fix it.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Pull request merged**
